# Generated by Django 4.2.30 on 2026-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformintegration',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('threads', 'Threads'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('reddit', 'Reddit')], max_length=20),
        ),
    ]
