# Generated by Django 4.2.30 on 2026-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_socialpost_scheduled_time_socialpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
