# Generated by Django 4.2.30 on 2026-05-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_platformintegration_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformintegration',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('threads', 'Threads'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('reddit', 'Reddit'), ('blogger', 'Blogger')], max_length=20),
        ),
    ]
