# Generated by Django 4.2.30 on 2026-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_platformintegration_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
        migrations.AlterField(
            model_name='platformintegration',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('threads', 'Threads'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('reddit', 'Reddit'), ('blogger', 'Blogger'), ('wordpress', 'WordPress'), ('tumblr', 'Tumblr'), ('discord', 'Discord')], max_length=20),
        ),
    ]
