# Generated by Django 4.2.30 on 2026-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_socialpost_image_file_socialpost_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
