# Generated by Django 4.2.30 on 2026-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_socialpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='error_message',
            field=models.TextField(blank=True, help_text='Stores the failure reason from the background worker', null=True),
        ),
    ]
