# Generated by Django 4.2.30 on 2026-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_socialpost_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
