# Generated by Django 4.2.27 on 2026-01-01 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokaccount',
            name='tiktok_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tiktokaccount',
            unique_together={('user', 'tiktok_id')},
        ),
    ]
