# Generated by Django 4.2.27 on 2026-01-01 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='youtubeaccount',
            unique_together={('user', 'channel_id')},
        ),
    ]
