# Generated by Django 5.2.5 on 2025-08-31 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.TextField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
