# Generated by Django 5.2.5 on 2025-08-31 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedinaccount',
            old_name='refresh_token',
            new_name='access_token',
        ),
    ]
