# Generated by Django 4.2.27 on 2026-01-01 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkedin', '0002_rename_refresh_token_linkedinaccount_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinaccount',
            name='linkedin_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='linkedinaccount',
            unique_together={('user', 'linkedin_id')},
        ),
    ]
